# Generated by Django 4.2.3 on 2023-07-11 19:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("weight", models.FloatField()),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="GoalModel",
            fields=[
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, primary_key=True, serialize=False
                    ),
                ),
                ("goal_achieved", models.BooleanField(default=False)),
                ("ml_consumed", models.IntegerField(default=0)),
                ("goal", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aqua_tally_api.usermodel",
                    ),
                ),
            ],
            options={
                "db_table": "goal",
            },
        ),
    ]
